#pragma once

#include "Animation.h"
#include "BehaviorTree.h"
#include "DesktopWorld.h"
#include "Memory.h"
#include "MouseSensor.h"
#include "Physics.h"
#include "SystemSensor.h"

#include <memory>
#include <string>

namespace VirtualPet {

/// High-level behavioral actions chosen by the pet brain.
enum class PetAction {
    Idle,
    Wandering,
    FollowingCursor,
    Sleeping,
    Dragged,
    ReactingToClick,
    ChasingToy,
    EatingTreat,
    StudyMode
};

/// Output intent generated by the companion brain each decision cycle.
struct BrainDecision {
    PetAction action{PetAction::Idle};
    AnimationState animState{AnimationState::Idle};
    float targetHorizontalSpeed{0.0f};  ///< Desired horizontal velocity in px/s.
    bool wantJump{false};                ///< Impulse request to jump.
    bool facingLeft{false};              ///< Desired sprite facing direction.
    std::string thought;                 ///< Current inner thoughts/state description.
};

/// Evaluated utility scores across candidate motivations.
struct UtilityScores {
    float sleepScore{0.0f};
    float eatScore{0.0f};
    float toyScore{0.0f};
    float followScore{0.0f};
    float wanderScore{0.0f};
    float idleScore{0.0f};
    float studyScore{0.0f};
};

/**
 * @brief Autonomous cognitive decision system combining Behavior Trees with Utility AI curves.
 */
class PetBrain {
public:
    PetBrain();
    void RequestAction(PetAction action, float duration = 1.8f);
    void RequestReaction(std::string thought, float duration = 1.8f);
    void Configure(float tickRate, float idleTimeout) { m_tickInterval = 1.0f / tickRate; m_actionDuration = idleTimeout; }
    void StartStudyMode(float duration = 120.0f);
    [[nodiscard]] bool IsInStudyMode() const noexcept { return m_studyModeTimer > 0.0f; }

    ~PetBrain() = default;

    /// Evaluates observations, computes utility scores, and selects optimal behavioral intent.
    BrainDecision Update(float deltaTime,
                         const MouseSensor& mouse,
                         const SystemSensor& system,
                         Memory& memory,
                         const DesktopWorld& world,
                         Physics& physics);

    [[nodiscard]] PetAction GetCurrentAction() const noexcept { return m_currentAction; }
    [[nodiscard]] const std::string& GetThought() const noexcept { return m_currentThought; }
    [[nodiscard]] const UtilityScores& GetLastScores() const noexcept { return m_lastScores; }

private:
    void BuildBehaviorTree();
    [[nodiscard]] UtilityScores CalculateUtilityScores(const Memory& memory,
                                                       const MouseSensor& mouse,
                                                       const SystemSensor& system,
                                                       const Physics& physics) const;

    std::unique_ptr<BehaviorTree> m_tree;
    PetAction m_currentAction{PetAction::Idle};
    std::string m_currentThought{"Sitting by your side keeping you company."};
    float m_studyModeTimer{0.0f};
    UtilityScores m_lastScores;

    float m_actionTimer{0.0f};
    float m_tickInterval{0.1f};
    float m_scoreTimer{0.0f};
    float m_contactCooldown{0.0f};
    bool m_manualSleep{false};
    float m_actionDuration{4.0f};
    int32_t m_wanderTargetX{0};
    bool m_facingLeft{false};
};

} // namespace VirtualPet
